version: "3.7"

services:
  mariadb:
    image: mariadb:latest 
    restart: always
    networks:
      - net
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: blabla 
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka

  pma:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    networks:
      - net
    ports:
      - "8080:80"
    links:
      - mariadb:db

  omeka:
    depends_on:
      - mariadb
    image: lafayettepubliclibrary/omeka-s:3.1.1
    restart: always
    networks:
      - net
    ports:
      - "88:80"
    links:
      - mariadb:db
    volumes:
      - omeka:/var/www/html/volume
volumes:
  mariadb:
  omeka:

networks:
  net:
