version: "3.7"

services:
  mariadb:
    image: mariadb:latest 
    restart: always
              
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: blabla 
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka

  pma:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin:latest
    restart: always
 #  ports:
 #    - "8080:80"
    links:
      - mariadb:db

  omeka:
    depends_on:
      - mariadb
    image: lafayettepubliclibrary/omeka-s:3.1.1
    restart: always

#   ports:
#     - "88:80"
    links:
      - mariadb:db
    volumes:
      - omeka:/var/www/html/volume
    environment:
      - VIRTUAL_HOST=example.lafayettepubliclibrary.org
      - LETSENCRYPT_HOST=example.lafayettepubliclibrary.org
volumes:
  mariadb:
  omeka:

networks:
 default:
   external: true
   name: net
